<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>السلة - Cart</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{{ asset('assets/css/cart.css') }}">
    <script>
        (function () {
            var lang = localStorage.getItem('language') || 'ar';
            document.documentElement.lang = lang;
            document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
        })();
    </script>
    <style>
        .delivery-info-section, .payment-method-section {
            margin-top: 20px;
            padding-top: 20px;
            border-top: 1px solid #eee;
            width: 100%;
            margin-bottom: 20px;
        }
        
        .delivery-info-section h3, .payment-method-section h3 {
            margin-bottom: 15px;
            font-size: 1.1em;
            color: #333;
        }
        
        .form-group {
            margin-bottom: 15px;
        }
        
        .form-group label {
            display: block;
            margin-bottom: 5px;
            font-weight: 500;
        }
        
        .form-input {
            width: 100%;
            padding: 10px;
            border: 1px solid #ddd;
            border-radius: 8px;
            font-family: inherit;
        }
        
        .address-input {
            height: 80px;
            resize: vertical;
        }
        
        .payment-options {
            display: flex;
            flex-direction: column;
            gap: 10px;
        }
        
        .payment-option {
            display: flex;
            align-items: center;
            gap: 10px;
            cursor: pointer;
            padding: 10px;
            border: 1px solid #ddd;
            border-radius: 8px;
            transition: all 0.2s;
        }
        
        .payment-option:hover {
            background-color: #f9f9f9;
        }
        
        .payment-option input[type="radio"] {
            width: 18px;
            height: 18px;
            accent-color: #4CAF50;
        }
    </style>
</head>
<body>
    <!-- Top Bar -->
    <div class="top-bar">
        <h1 class="cart-title" lang="ar">السلة</h1>
        <h1 class="cart-title hidden" lang="en">Cart</h1>
        <div class="language-selector">
            <button class="language-btn" id="languageBtn" onclick="toggleLanguage()">
                <span lang="ar">English</span>
                <span lang="en" class="hidden">العربية</span>
            </button>
        </div>
    </div>

    <!-- Cart Container -->
    <div class="cart-container">
        <div class="cart-items" id="cartItems">
            <!-- Cart items will be generated by JavaScript -->
        </div>

        <!-- Empty Cart Message -->
        <div class="empty-cart hidden" id="emptyCart">
            <div class="empty-cart-icon">
                <i class="fa fa-shopping-cart"></i>
            </div>
            <p lang="ar">السلة فارغة</p>
            <p lang="en" class="hidden">Your cart is empty</p>
        </div>

        <!-- Cart Summary -->
        <div class="cart-summary" id="cartSummary">
            <div class="summary-row">
                <span lang="ar">عدد العناصر:</span>
                <span lang="en" class="hidden">Items:</span>
                <span id="totalItems">0</span>
            </div>
            <div class="notes-section">
                <label class="notes-label" for="orderNotes">
                    <span lang="ar">ملاحظات الطلب:</span>
                    <span lang="en" class="hidden">Order Notes:</span>
                </label>
                <textarea 
                    id="orderNotes" 
                    class="notes-textarea"
                ></textarea>
            </div>

            <!-- Delivery Information Section -->
            <div class="delivery-info-section">
                <h3 lang="ar">معلومات التوصيل</h3>
                <h3 lang="en" class="hidden">Delivery Information</h3>
                
                <div class="form-group">
                    <label lang="ar">الاسم *</label>
                    <label lang="en" class="hidden">Name *</label>
                    <input type="text" id="customerName" class="form-input" required>
                </div>
                
                <div class="form-group">
                    <label lang="ar">رقم الهاتف *</label>
                    <label lang="en" class="hidden">Phone Number *</label>
                    <input type="tel" id="customerPhone" class="form-input" required>
                </div>
                
                <div class="form-group">
                    <label lang="ar">العنوان *</label>
                    <label lang="en" class="hidden">Address *</label>
                    <textarea id="customerAddress" class="form-input address-input" required></textarea>
                </div>
            </div>

            <!-- Payment Method Section -->
            <div class="payment-method-section">
                <h3 lang="ar">وسيلة الدفع</h3>
                <h3 lang="en" class="hidden">Payment Method</h3>
                
                <div class="payment-options">
                    <label class="payment-option">
                        <input type="radio" name="paymentMethod" value="benefit" checked>
                        <span lang="ar">بنفت</span>
                        <span lang="en" class="hidden">Benefit</span>
                    </label>
                    
                    <label class="payment-option">
                        <input type="radio" name="paymentMethod" value="card_on_delivery">
                        <span lang="ar">بطاقة عند الاستلام</span>
                        <span lang="en" class="hidden">Card on Delivery</span>
                    </label>
                    
                    <label class="payment-option">
                        <input type="radio" name="paymentMethod" value="cash_on_delivery">
                        <span lang="ar">كاش عند الاستلام</span>
                        <span lang="en" class="hidden">Cash on Delivery</span>
                    </label>
                </div>
            </div>

            <div class="summary-total">
                <span lang="ar">المجموع:</span>
                <span lang="en" class="hidden">Total:</span>
                <span id="totalPrice">0.00 د.ب</span>
            </div>
            <button class="checkout-btn" onclick="checkout()" id="checkoutBtn">
                <span lang="ar">إتمام الطلب</span>
                <span lang="en" class="hidden">Checkout</span>
            </button>
        </div>
    </div>

    <script>
        let currentLanguage = localStorage.getItem('language') || 'ar';
        let cart = [];

        // Load cart from localStorage
        function loadCart() {
            const savedCart = localStorage.getItem('restaurantCart');
            if (savedCart) {
                cart = JSON.parse(savedCart);
            }
            renderCart();
        }

        // Save cart to localStorage
        function saveCart() {
            localStorage.setItem('restaurantCart', JSON.stringify(cart));
            renderCart();
        }

        // Set language (used for initialization)
        function setLanguage(lang) {
            currentLanguage = lang;
            localStorage.setItem('language', lang);
            document.documentElement.lang = lang;
            document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
            document.body.setAttribute('dir', lang === 'ar' ? 'rtl' : 'ltr');

            document.querySelectorAll('[lang="ar"]').forEach(el => {
                el.classList.toggle('hidden', lang !== 'ar');
            });
            document.querySelectorAll('[lang="en"]').forEach(el => {
                el.classList.toggle('hidden', lang !== 'en');
            });

            // Update notes placeholder
            const notesTextarea = document.getElementById('orderNotes');
            if (notesTextarea) {
                notesTextarea.placeholder = lang === 'ar' 
                    ? 'أضف ملاحظات خاصة للطلب...' 
                    : 'Add special notes for your order...';
            }
            
            // Update placeholders for delivery info
            const nameInput = document.getElementById('customerName');
            const phoneInput = document.getElementById('customerPhone');
            const addressInput = document.getElementById('customerAddress');
            
            if (nameInput) nameInput.placeholder = lang === 'ar' ? 'أدخل اسمك' : 'Enter your name';
            if (phoneInput) phoneInput.placeholder = lang === 'ar' ? 'أدخل رقم هاتفك' : 'Enter your phone number';
            if (addressInput) addressInput.placeholder = lang === 'ar' ? 'أدخل عنوان التوصيل بالتفصيل' : 'Enter detailed delivery address';

            renderCart();
        }

        // Toggle language (used for button click)
        function toggleLanguage() {
            const newLang = currentLanguage === 'ar' ? 'en' : 'ar';
            setLanguage(newLang);
        }

        // Render cart items
        function renderCart() {
            const cartItems = document.getElementById('cartItems');
            const emptyCart = document.getElementById('emptyCart');
            const cartSummary = document.getElementById('cartSummary');

            if (cart.length === 0) {
                cartItems.innerHTML = '';
                emptyCart.classList.remove('hidden');
                cartSummary.classList.add('hidden');
                return;
            }

            emptyCart.classList.add('hidden');
            cartSummary.classList.remove('hidden');

            cartItems.innerHTML = cart.map((item, index) => `
                <div class="cart-item">
                    <img src="${item.image}" 
                         alt="${item.name}" 
                         class="cart-item-image"
                         onerror="this.src='data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 width=%22100%22 height=%22100%22%3E%3Crect fill=%22%23f0f0f0%22 width=%22100%22 height=%22100%22/%3E%3C/svg%3E'">
                    <div class="cart-item-content">
                        <div class="cart-item-header">
                            <div class="cart-item-name">${item.name}</div>
                            <div class="cart-item-price">
                                ${item.price.toFixed(2)} ${currentLanguage === 'ar' ? 'د.ب' : 'BHD'}
                            </div>
                        </div>
                        <div class="cart-item-controls">
                            <div class="quantity-controls">
                                <button class="quantity-btn" onclick="decreaseQuantity(${index})">-</button>
                                <span class="quantity-value">${item.quantity}</span>
                                <button class="quantity-btn" onclick="increaseQuantity(${index})">+</button>
                            </div>
                            <button class="remove-btn" onclick="removeItem(${index})">
                                <i class="fa fa-trash"></i>
                            </button>
                        </div>
                    </div>
                </div>
            `).join('');

            // Update language visibility
            document.querySelectorAll('[lang="ar"]').forEach(el => {
                el.classList.toggle('hidden', currentLanguage !== 'ar');
            });
            document.querySelectorAll('[lang="en"]').forEach(el => {
                el.classList.toggle('hidden', currentLanguage !== 'en');
            });

            // Update summary
            updateSummary();
        }

        // Update quantity
        function increaseQuantity(index) {
            cart[index].quantity += 1;
            saveCart();
        }

        function decreaseQuantity(index) {
            if (cart[index].quantity > 1) {
                cart[index].quantity -= 1;
                saveCart();
            } else {
                removeItem(index);
            }
        }

        // Remove item
        function removeItem(index) {
            cart.splice(index, 1);
            saveCart();
        }

        // Update summary
        function updateSummary() {
            const totalItems = cart.reduce((sum, item) => sum + item.quantity, 0);
            const totalPrice = cart.reduce((sum, item) => sum + (item.price * item.quantity), 0);

            const totalItemsEl = document.getElementById('totalItems');
            const totalPriceEl = document.getElementById('totalPrice');
            
            if (totalItemsEl) {
                totalItemsEl.textContent = totalItems;
            }
            
            if (totalPriceEl) {
                totalPriceEl.textContent = `${totalPrice.toFixed(2)} ${currentLanguage === 'ar' ? 'د.ب' : 'BHD'}`;
            }
        }

        // Format order message
        function formatOrderMessage() {
            const totalPrice = cart.reduce((sum, item) => sum + (item.price * item.quantity), 0);
            const totalItems = cart.reduce((sum, item) => sum + item.quantity, 0);
            const notes = document.getElementById('orderNotes').value.trim();
            
            // Get Customer Info
            const name = document.getElementById('customerName').value.trim();
            const phone = document.getElementById('customerPhone').value.trim();
            const address = document.getElementById('customerAddress').value.trim();
            
            // Get Payment Method
            const paymentMethodEl = document.querySelector('input[name="paymentMethod"]:checked');
            const paymentMethodValue = paymentMethodEl ? paymentMethodEl.value : 'benefit';
            
            let paymentMethodAr = '';
            let paymentMethodEn = '';
            
            switch(paymentMethodValue) {
                case 'benefit':
                    paymentMethodAr = 'بنفت';
                    paymentMethodEn = 'Benefit';
                    break;
                case 'card_on_delivery':
                    paymentMethodAr = 'بطاقة عند الاستلام';
                    paymentMethodEn = 'Card on Delivery';
                    break;
                case 'cash_on_delivery':
                    paymentMethodAr = 'كاش عند الاستلام';
                    paymentMethodEn = 'Cash on Delivery';
                    break;
            }
            
            // Group items by restaurant
            const itemsByRestaurant = {};
            cart.forEach(item => {
                const restaurantId = item.restaurantId || 'unknown';
                const restaurantName = item.restaurantName || (currentLanguage === 'ar' ? 'غير محدد' : 'Unknown');
                
                if (!itemsByRestaurant[restaurantId]) {
                    itemsByRestaurant[restaurantId] = {
                        name: restaurantName,
                        nameAr: item.restaurantNameAr || 'غير محدد',
                        nameEn: item.restaurantNameEn || 'Unknown',
                        items: []
                    };
                }
                itemsByRestaurant[restaurantId].items.push(item);
            });
            
            let message = '';
            
            if (currentLanguage === 'ar') {
                message += '*طلب جديد*\n';
                message += '═══════════════════\n\n';
                
                // Customer Info
                message += '*معلومات العميل:*\n';
                message += `الاسم: ${name}\n`;
                message += `رقم الهاتف: ${phone}\n`;
                message += `العنوان: ${address}\n`;
                message += `وسيلة الدفع: ${paymentMethodAr}\n\n`;
                message += '═══════════════════\n\n';
                
                // Group by restaurant
                const restaurantIds = Object.keys(itemsByRestaurant);
                restaurantIds.forEach((restaurantId, restaurantIndex) => {
                    const restaurant = itemsByRestaurant[restaurantId];
                    const restaurantName = currentLanguage === 'ar' ? restaurant.nameAr : restaurant.nameEn;
                    
                    message += `*المطعم: ${restaurantName}*\n`;
                    message += '───────────────────\n';
                    
                    let restaurantTotal = 0;
                    restaurant.items.forEach((item, index) => {
                        const itemTotal = (item.price * item.quantity);
                        restaurantTotal += itemTotal;
                        message += `${index + 1}. ${item.name}\n`;
                        message += `   الكمية: ${item.quantity} × ${item.price.toFixed(2)} د.ب = ${itemTotal.toFixed(2)} د.ب\n\n`;
                    });
                    
                    message += `*المجموع الفرعي: ${restaurantTotal.toFixed(2)} د.ب*\n`;
                    
                    if (restaurantIndex < restaurantIds.length - 1) {
                        message += '\n';
                    }
                });
                
                message += '\n═══════════════════\n';
                message += `*عدد العناصر:* ${totalItems}\n`;
                message += `*المجموع الكلي:* ${totalPrice.toFixed(2)} د.ب\n`;
                
                if (notes) {
                    message += '\n*ملاحظات الطلب:*\n';
                    message += `${notes}\n`;
                }
                
                message += '\n═══════════════════\n';
                message += 'شكراً لطلبك! 🙏';
            } else {
                message += '*New Order*\n';
                message += '═══════════════════\n\n';
                
                // Customer Info
                message += '*Customer Information:*\n';
                message += `Name: ${name}\n`;
                message += `Phone: ${phone}\n`;
                message += `Address: ${address}\n`;
                message += `Payment Method: ${paymentMethodEn}\n\n`;
                message += '═══════════════════\n\n';
                
                // Group by restaurant
                const restaurantIds = Object.keys(itemsByRestaurant);
                restaurantIds.forEach((restaurantId, restaurantIndex) => {
                    const restaurant = itemsByRestaurant[restaurantId];
                    const restaurantName = currentLanguage === 'ar' ? restaurant.nameAr : restaurant.nameEn;
                    
                    message += `*Restaurant: ${restaurantName}*\n`;
                    message += '───────────────────\n';
                    
                    let restaurantTotal = 0;
                    restaurant.items.forEach((item, index) => {
                        const itemTotal = (item.price * item.quantity);
                        restaurantTotal += itemTotal;
                        message += `${index + 1}. ${item.name}\n`;
                        message += `   Quantity: ${item.quantity} × ${item.price.toFixed(2)} BHD = ${itemTotal.toFixed(2)} BHD\n\n`;
                    });
                    
                    message += `*Subtotal: ${restaurantTotal.toFixed(2)} BHD*\n`;
                    
                    if (restaurantIndex < restaurantIds.length - 1) {
                        message += '\n';
                    }
                });
                
                message += '\n═══════════════════\n';
                message += `*Total Items:* ${totalItems}\n`;
                message += `*Total Amount:* ${totalPrice.toFixed(2)} BHD\n`;
                
                if (notes) {
                    message += '\n*Order Notes:*\n';
                    message += `${notes}\n`;
                }
                
                message += '\n═══════════════════\n';
                message += 'Thank you for your order! 🙏';
            }
            
            return message;
        }

        // Checkout
        function checkout() {
            if (cart.length === 0) {
                alert(currentLanguage === 'ar' ? 'السلة فارغة' : 'Cart is empty');
                return;
            }
            
            // Validate Customer Info
            const name = document.getElementById('customerName').value.trim();
            const phone = document.getElementById('customerPhone').value.trim();
            const address = document.getElementById('customerAddress').value.trim();
            
            if (!name || !phone || !address) {
                alert(currentLanguage === 'ar' 
                    ? 'الرجاء ملء جميع معلومات التوصيل المطلوبة (الاسم، الهاتف، العنوان)' 
                    : 'Please fill in all required delivery information (Name, Phone, Address)');
                return;
            }

            const orderMessage = formatOrderMessage();
            const phoneNumber = '+97338131338';
            const whatsappUrl = `https://wa.me/${phoneNumber}?text=${encodeURIComponent(orderMessage)}`;
            
            // Open WhatsApp
            window.open(whatsappUrl, '_blank');
            
            // Clear cart after sending
            setTimeout(() => {
                if (confirm(currentLanguage === 'ar' 
                    ? 'هل تريد مسح السلة بعد إرسال الطلب؟' 
                    : 'Do you want to clear the cart after sending the order?')) {
                    cart = [];
                    document.getElementById('orderNotes').value = '';
                    saveCart();
                }
            }, 1000);
        }

        // Initialize
        loadCart();
        setLanguage(currentLanguage);
    </script>
</body>
</html>
